version: 2
release:
  github:
    owner: sfphinx
    name: tribaloutpost-auto-downloader
before:
  hooks:
    - go generate ./...
builds:
  - id: tribaloutpost-adl
    binary: tribaloutpost-adl
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-windows-gnu
        ldflags:
          - -s -w -H windowsgui -extldflags '-Wl,--subsystem,windows'
          - -X '{{ .ModulePath }}/pkg/common.SUMMARY=v{{ .Version }}'
          - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
          - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
          - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
          - -X '{{ .ModulePath }}/pkg/common.ADLKey={{ .Env.ADL_KEY }}'
          - -X '{{ .ModulePath }}/pkg/signing.PublicKeyBase64={{ .Env.ADL_PUBLIC_KEY }}'
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X '{{ .ModulePath }}/pkg/common.SUMMARY=v{{ .Version }}'
      - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
      - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
      - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
      - -X '{{ .ModulePath }}/pkg/common.ADLKey={{ .Env.ADL_KEY }}'
      - -X '{{ .ModulePath }}/pkg/signing.PublicKeyBase64={{ .Env.ADL_PUBLIC_KEY }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
sboms:
  - artifacts: archive
archives:
  - id: tribaloutpost-adl
    builds:
      - tribaloutpost-adl
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    format_overrides:
      - goos: windows
        format: zip
signs:
  - ids:
      - default
    cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      [
        "sign-blob",
        "--yes",
        "--oidc-provider=github",
        "--oidc-issuer=https://token.actions.githubusercontent.com",
        "--output-certificate=${certificate}",
        "--output-signature=${signature}",
        "${artifact}",
      ]
    artifacts: all
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: '{{ trimprefix .Summary "v" }}'
changelog:
  disable: true
